import type { ToolMetadata, VirtualFileSystem } from "./types.js";
import { jsDoc, jsonSchemaToType } from "./schema.js";

export interface GeneratedSdk {
  files: Record<string, string>;
  prompt: string;
}

export function generateSdk(metadata: ToolMetadata[], options: { sdkDir: string; workdir: string; promptSuffix?: string }): GeneratedSdk {
  const { sdkDir, workdir, promptSuffix } = options;
  const files: Record<string, string> = {
    [`${sdkDir}/tools.js`]: generateToolsJs(metadata),
    [`${sdkDir}/tools.d.ts`]: generateToolsDts(metadata),
    [`${sdkDir}/globals.d.ts`]: generateGlobalsDts(metadata),
    [`${sdkDir}/fs.js`]: generateFsJs(),
    [`${sdkDir}/fs.d.ts`]: generateFsDts(),
    [`${sdkDir}/README.md`]: generateReadme(metadata, { sdkDir, workdir }),
    [`${workdir}/README.md`]: generateWorkspaceReadme({ sdkDir, workdir }),
  };

  return {
    files,
    prompt: generatePrompt(metadata, { sdkDir, workdir, promptSuffix }),
  };
}

export function installSdk(fs: VirtualFileSystem, generated: GeneratedSdk): void {
  for (const pathname of Object.keys(generated.files).sort()) {
    const parent = pathname.slice(0, pathname.lastIndexOf("/")) || "/";
    fs.mkdir(parent, { recursive: true });
    fs.writeFile(pathname, generated.files[pathname] ?? "");
  }
}

function generateToolsJs(metadata: ToolMetadata[]): string {
  const exports = metadata
    .map(
      (tool) => `export async function ${tool.identifier}(input) {\n  return await globalThis.__codeTools.callTool(${JSON.stringify(
        tool.originalName,
      )}, input);\n}`,
    )
    .join("\n\n");

  const objectEntries = metadata.map((tool) => `${JSON.stringify(tool.originalName)}: ${tool.identifier}`).join(",\n  ");

  return `// Generated by code-tools. Do not edit.\n${exports}\n\nexport const tools = Object.freeze({\n  ${objectEntries}\n});\n`;
}

function generateToolsDts(metadata: ToolMetadata[]): string {
  const chunks: string[] = ["// Generated by code-tools. Do not edit."];
  for (const tool of metadata) {
    if (tool.description) chunks.push(jsDoc(tool.description));
    chunks.push(`export type ${tool.inputTypeName} = ${jsonSchemaToType(tool.inputJsonSchema, tool.inputJsonSchema)};`);
    chunks.push(
      `export type ${tool.outputTypeName} = ${tool.outputJsonSchema ? jsonSchemaToType(tool.outputJsonSchema, tool.outputJsonSchema) : "unknown"};`,
    );
    chunks.push(`export declare function ${tool.identifier}(input: ${tool.inputTypeName}): Promise<${tool.outputTypeName}>;`);
    chunks.push("");
  }

  chunks.push("export declare const tools: {");
  for (const tool of metadata) {
    chunks.push(`  readonly ${JSON.stringify(tool.originalName)}: typeof ${tool.identifier};`);
  }
  chunks.push("};");
  chunks.push("");
  chunks.push('declare module "tools" {');
  for (const tool of metadata) {
    chunks.push(`  export type ${tool.inputTypeName} = import("./tools.js").${tool.inputTypeName};`);
    chunks.push(`  export type ${tool.outputTypeName} = import("./tools.js").${tool.outputTypeName};`);
    chunks.push(`  export const ${tool.identifier}: typeof import("./tools.js").${tool.identifier};`);
  }
  chunks.push('  export const tools: typeof import("./tools.js").tools;');
  chunks.push("}");
  chunks.push("");
  return chunks.join("\n");
}

function generateGlobalsDts(metadata: ToolMetadata[]): string {
  const chunks = ["// Generated by code-tools. Do not edit.", 'import type * as CodeToolsGeneratedTools from "./tools.js";', "", "declare global {"];
  for (const tool of metadata) {
    chunks.push(`  const ${tool.identifier}: typeof CodeToolsGeneratedTools.${tool.identifier};`);
  }
  chunks.push("  const tools: typeof CodeToolsGeneratedTools.tools;");
  chunks.push("}");
  chunks.push("");
  chunks.push("export {};", "");
  return chunks.join("\n");
}

function generateFsJs(): string {
  return `// Generated by code-tools. Do not edit.\nasync function fs(op, ...args) {\n  return await globalThis.__codeTools.fs(op, args);\n}\n\nexport const cwd = () => fs("cwd");\nexport const chdir = (path) => fs("chdir", path);\nexport const exists = (path) => fs("exists", path);\nexport const stat = (path) => fs("stat", path);\nexport const readFile = (path) => fs("readFile", path);\nexport const writeFile = (path, contents) => fs("writeFile", path, contents);\nexport const readdir = (path = ".") => fs("readdir", path);\nexport const mkdir = (path, options = {}) => fs("mkdir", path, options);\nexport const rm = (path, options = {}) => fs("rm", path, options);\nexport const rename = (from, to) => fs("rename", from, to);\n`;
}

function generateFsDts(): string {
  return `// Generated by code-tools. Do not edit.\nexport interface FsStat { path: string; type: "file" | "directory"; size: number; }\nexport interface FsDirent extends FsStat { name: string; }\nexport declare const cwd: () => Promise<string>;\nexport declare const chdir: (path: string) => Promise<string>;\nexport declare const exists: (path: string) => Promise<boolean>;\nexport declare const stat: (path: string) => Promise<FsStat>;\nexport declare const readFile: (path: string) => Promise<string>;\nexport declare const writeFile: (path: string, contents: string) => Promise<void>;\nexport declare const readdir: (path?: string) => Promise<FsDirent[]>;\nexport declare const mkdir: (path: string, options?: { recursive?: boolean }) => Promise<void>;\nexport declare const rm: (path: string, options?: { recursive?: boolean; force?: boolean }) => Promise<void>;\nexport declare const rename: (from: string, to: string) => Promise<void>;\n\ndeclare module "sandbox:fs" {\n  export * from "./fs.js";\n}\n`;
}

function generateReadme(metadata: ToolMetadata[], options: { sdkDir: string; workdir: string }): string {
  const lines = [
    "# code-tools generated SDK",
    "",
    `SDK directory: \`${options.sdkDir}\``,
    `Writable workspace: \`${options.workdir}\``,
    "",
    "You can call tools as top-level globals in the code sandbox, or import them:",
    "",
    "```ts",
    'import { tools } from "tools";',
    "// or: import { someTool } from \"tools\";",
    "```",
    "",
    "Virtual filesystem helpers are available from `sandbox:fs`.",
    "",
    "```ts",
    'import { readFile, writeFile, readdir } from "sandbox:fs";',
    "```",
    "",
    "Use these generated files to explore tool names, input types, and output types. Do not call source tools just to discover their schemas.",
    "",
    "For large results, save raw outputs/artifacts in the workspace and print only concise summaries plus file paths.",
    "",
    "## Tools",
    "",
  ];

  for (const tool of metadata) {
    lines.push(`### ${tool.identifier}`);
    if (tool.originalName !== tool.identifier) lines.push(`Original tool name: \`${tool.originalName}\``);
    if (tool.description) lines.push("", tool.description);
    lines.push("", "```ts");
    lines.push(`type ${tool.inputTypeName} = ${jsonSchemaToType(tool.inputJsonSchema, tool.inputJsonSchema)};`);
    lines.push(`type ${tool.outputTypeName} = ${tool.outputJsonSchema ? jsonSchemaToType(tool.outputJsonSchema, tool.outputJsonSchema) : "unknown"};`);
    lines.push(`declare function ${tool.identifier}(input: ${tool.inputTypeName}): Promise<${tool.outputTypeName}>;`);
    lines.push("```", "");
  }

  return `${lines.join("\n")}\n`;
}

function generateWorkspaceReadme(options: { sdkDir: string; workdir: string }): string {
  return `# Workspace\n\nThis directory is writable and persists between bash/code calls in this code-tools session.\n\nGenerated SDK files are mounted at \`${options.sdkDir}\`. Start with:\n\n\`\`\`bash\ncat ${options.sdkDir}/README.md\ncat ${options.sdkDir}/tools.d.ts\n\`\`\`\n\nUse generated SDK files for type/schema discovery. Save large raw outputs here and print concise summaries plus file paths.\n`;
}

function generatePrompt(metadata: ToolMetadata[], options: { sdkDir: string; workdir: string; promptSuffix?: string }): string {
  const signatures = metadata
    .map((tool) => {
      const input = compact(jsonSchemaToType(tool.inputJsonSchema, tool.inputJsonSchema));
      const output = compact(tool.outputJsonSchema ? jsonSchemaToType(tool.outputJsonSchema, tool.outputJsonSchema) : "unknown");
      const description = tool.description ? ` // ${tool.description.replace(/\s+/g, " ")}` : "";
      return `- ${tool.identifier}(input: ${input}): Promise<${output}>${description}`;
    })
    .join("\n");

  return [
    "You have access to a local code-tools sandbox through exactly two tools: `bash` and `code`.",
    `State persists in the shared virtual filesystem. Use ${options.workdir} for your own files.`,
    `Generated tool SDK files are mounted read-only by convention at ${options.sdkDir}. Inspect them with bash, e.g. \`cat ${options.sdkDir}/README.md\` or \`cat ${options.sdkDir}/tools.d.ts\`.`,
    "Use the generated SDK files for tool/type/schema exploration; do not call hidden source tools just to discover their schemas.",
    `For large tool results or intermediate data, write raw outputs to files under ${options.workdir} and print only concise summaries plus file paths to save tokens.`,
    "The code sandbox has no network, no npm installs, no Node built-ins, and no host filesystem access.",
    "In the code sandbox, hidden source tools are callable as top-level async functions and are also importable from the virtual module `tools`.",
    "For virtual filesystem access inside code, import from `sandbox:fs`.",
    "Available top-level tool functions:",
    signatures || "- (none)",
    options.promptSuffix ?? "",
  ]
    .filter(Boolean)
    .join("\n");
}

function compact(type: string): string {
  return type.replace(/\s+/g, " ").trim();
}
